version: "3.9"

services:
  forgebyteslab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4173"
    environment:
      NODE_ENV: production
    restart: unless-stopped
